#!/bin/bash

LOCAL=/home/sievers/local/
#MKL=/opt/intel/Compiler/11.0/081/mkl/
#IOMP=/opt/intel/Compiler/11.0/081/lib/intel64/


#JEMALLOC=/home/sievers/util/jemalloc_linux/
#FFTWLIB=/home/sievers/util/fftw-3.1.2/gcc/

#BLASLIB=/opt/intel/Compiler/11.0/081/mkl/lib/em64t/
#INTEL=/opt/intel/Compiler/11.0/081/lib/intel64/


#/cita/d/raid-sievers/sievers/tpb/GotoBLAS

#CBLASDIR=/cita/d/raid-sievers/sievers/tpb/CBLAS
#CBLASLIB=${CBLASDIR}/lib
#CBLASINC=${CBLASDIR}/src

#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64/lam:/usr/lib/lam

#IDIRS="-I../include -I${FFTWLIB}/include -I$LOCAL/include -I$CBLASINC"
ZDIR=/home/nolta/act/zirfile/local
IDIRS="-I${ZDIR}/include -I../include -I${LOCAL}/include -I${MKL}/include -fopenmp"
#LDIRS="-L${FFTWLIB}/lib -L${LOCAL}/lib -L$CBLASLIB -L$BLASLIB -L${JEMALLOC}"
#LDIRS=" -L${LOCAL}/lib -L${BLASLIB} -L${INTEL}"
LDIRS=" -L${ZDIR}/lib -lzzip -L${LOCAL}/lib " 
#-L${MKL}/lib/em64t/ -L${IOMP}"

#PREFIX=/cita/d/raid-sievers/sievers/act/ninkasi/
PREFIX=/home/sievers/local/




#./configure CC=$LOCAL/opt/openmpi/bin/mpicc \
#    MPICC=$LOCAL/opt/openmpi/bin/mpicc \
#    CPPFLAGS="-I$ACT_LOCAL/include -I$MKLROOT/include -I$MKLROOT/include/fftw" \
#    LDFLAGS="-L$ACT_LOCAL/lib -L$MKLROOT/lib/em64t -lmkl -liomp5 -lpthread -lfftw3xc_intel" \
#    --prefix=$ACT_LOCAL \
#    --enable-static



./configure CPPFLAGS="$IDIRS" LDFLAGS="$LDIRS -llapack -lgoto2  -lpthread" --prefix=${PREFIX}   --enable-actdata-double  --enable-static

